name: summa_logos
description: Summa Logos Project

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  progress_hud: ^1.1.0
#  flutter_facebook_login: ^1.1.1
  device_info: ^0.4.1+4
  url_launcher: ^5.4.1
  flutter_webview_plugin: ^0.3.10+1
#  firebase_messaging: ^2.1.0
  sqflite: any
  path_provider: any
  http: ^0.12.0+4
#  carousel_slider: ^1.0.1
#  carousel_pro: ^0.0.1
  xml2json: ^4.1.1
  shared_preferences: ^0.5.6+1
  google_sign_in: ^4.1.1
  fluttertoast: ^3.1.3
  flutter_launcher_icons: ^0.7.4
  flutter_spinkit: ^4.1.1+1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "./images/ic_summa_logos.png"
  android: true
  ios: true


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - images/faith-can-move-mountains.png
    - images/fb_icon.png
    - images/google_icon.png
    - images/rain.jpg
    - images/walk_by_faith.jpg
    - images/verse.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
      - family: Montserrat
        fonts:
          - asset: fonts/Montserrat-Medium.ttf
          - asset: fonts/Montserrat-Bold.ttf
            weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
