class Autogenerated {
  Bible bible;

  Autogenerated({this.bible});

  Map<String, dynamic> toMap() {
    var map = new Map<String, dynamic>();
    map["bible"] = bible;
    return map;
  }

  Autogenerated.fromMap(Map<String, dynamic> map)
      : bible = map['bible'] != null ? new Bible.fromMap(map['bible']) : null;

//  Autogenerated.fromJson(Map<String, dynamic> json) {
//    bible = json['bible'] != null ? new Bible.fromJson(json['bible']) : null;
//  }

//  Map<String, dynamic> toJson() {
//    final Map<String, dynamic> data = new Map<String, dynamic>();
//    if (this.bible != null) {
//      data['bible'] = this.bible.toJson();
//    }
//    return data;
//  }
}

class Bible {
  String title;
  List<Book> bookList;
  Book book;

  Bible({this.title, this.bookList, this.book});

  Map<String, dynamic> toMap() {
    var map = new Map<String, dynamic>();
    map["title"] = title;
    if (bookList != null) map['book'] = bookList;
    else map['book'] = book;
    return map;
  }

  Bible.fromMap(Map<String, dynamic> map) {
    title = map['title'];

    if (map['book'] != null) {
      bookList = new List<Book>();
      if (map['book'] is List) {
        map['book'].forEach((v) {
          bookList.add(new Book.fromMap(v));
        });
      } else {
        book = new Book.fromMap(map['book']);
      }
    }
  }




//  Bible.fromJson(Map<String, dynamic> json) {
//    title = json['title'];
//    if (json['book'] != null) {
//      book = new List<Book>();
//      json['book'].forEach((v) {
//        book.add(new Book.fromJson(v));
//      });
//    }
//  }

//  Map<String, dynamic> toJson() {
//    final Map<String, dynamic> data = new Map<String, dynamic>();
//    data['title'] = this.title;
//    if (this.book != null) {
//      data['book'] = this.book.map((v) => v.toJson()).toList();
//    }
//    return data;
//  }
}

class Book {
  String bookId;
  String title;
  Chapter chapter;
  String name;

  Book({this.bookId, this.title, this.chapter});

  Map<String, dynamic> toMap() {
    var map = new Map<String, dynamic>();
    map["book_id"] = bookId;
    map["title"] = title;
    map["chapter"] = chapter;
    map["name"] = name;

    return map;
  }


  Book.fromMap(Map<String, dynamic> map) {
    bookId = map['book_id'];
    title = map['title'];
    name = map['name'];
    chapter =
    map['chapter'] != null ? new Chapter.fromMap(map['chapter']) : null;
  }
//
//  Book.fromJson(Map<String, dynamic> json) {
//    bookId = json['book_id'];
//    title = json['title'];
//    chapter =
//    json['chapter'] != null ? new Chapter.fromJson(json['chapter']) : null;
//  }

//  Map<String, dynamic> toJson() {
//    final Map<String, dynamic> data = new Map<String, dynamic>();
//    data['book_id'] = this.bookId;
//    data['title'] = this.title;
//    if (this.chapter != null) {
//      data['chapter'] = this.chapter.toJson();
//    }
//    return data;
//  }
}

class Chapter {
  String chap;
  Verses verses;

  Chapter({this.chap, this.verses});

  Map<String, dynamic> toMap() {
    var map = new Map<String, dynamic>();
    map["chap"] = chap;
    map["verses"] = verses;
    return map;
  }

  Chapter.fromMap(Map<String, dynamic> map) {
    chap = map['chap'];
    verses =
    map['verses'] != null ? new Verses.fromMap(map['verses']) : null;
  }

//  Chapter.fromJson(Map<String, dynamic> json) {
//    chap = json['chap'];
//    verses =
//    json['verses'] != null ? new Verses.fromJson(json['verses']) : null;
//  }

//  Map<String, dynamic> toJson() {
//    final Map<String, dynamic> data = new Map<String, dynamic>();
//    data['chap'] = this.chap;
//    if (this.verses != null) {
//      data['verses'] = this.verses.toJson();
//    }
//    return data;
//  }
}

class Verses {
  List<Verse> verseList;
  Verse verse;

  Verses({this.verseList, this.verse});

//  Verses.fromMap(Map<String, dynamic> map) {
//    verse = map['verse'] != null ? new Verse.fromJson(map['verse']) : null;
//  }


  Map<String, dynamic> toMap() {
    var map = new Map<String, dynamic>();
    if (verseList != null) {
      map['verse'] = verseList;
    } else map['verse'] = verse;
    return map;
  }

  Verses.fromMap(Map<String, dynamic> map) {
    if (map['verse'] != null) {
      if (map['verse'] is List) {
        verseList = new List<Verse>();
        map['verse'].forEach((v) {
          verseList.add(new Verse.fromMap(v));
        });
      } else {
        verse = new Verse.fromMap(map['verse']);
      }
    }
  }

//  Verses.fromMap(Map<String, dynamic> map) {
//    if (map['verse'] != null) {
//      verse = new List<Verse>();
//      map['verse'].forEach((v) {
//        verse.add(new Verse.fromMap(v));
//      });
//    }
//  }
//  Verses.fromJson(Map<String, dynamic> json) {
//    verse = json['verse'] != null ? new Verse.fromJson(json['verse']) : null;
//  }

//  Map<String, dynamic> toJson() {
//    final Map<String, dynamic> data = new Map<String, dynamic>();
//    if (this.verse != null) {
//      data['verse'] = this.verse.toJson();
//    }
//    return data;
//  }
}

class Verse {
  String number;
  String text;

  Verse({this.number, this.text});

  Map<String, dynamic> toMap() {
    var map = new Map<String, dynamic>();
    map["number"] = number;
    map["text"] = text;
    return map;
  }

  Verse.fromMap(Map<String, dynamic> map) {
    number = map['number'];
    text = map['text'];
  }

//  Verse.fromJson(Map<String, dynamic> json) {
//    number = json['number'];
//    text = json['text'];
//  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['number'] = this.number;
    data['text'] = this.text;
    return data;
  }
}
